// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1571.NewRobot.subsystems;

import org.usfirst.frc1571.NewRobot.RobotMap;
import org.usfirst.frc1571.NewRobot.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class armMotor extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController armMotorController1 = RobotMap.armMotorarmMotorController1;
    SpeedController armMotorController2 = RobotMap.armMotorarmMotorController2;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void armStop() {
    	armMotorController1.set(0.0);
    	armMotorController2.set(0.0);
    }
    
    public void armUp() {
    	armMotorController1.set(1.0);
    	armMotorController2.set(-1.0);
    }
    
    public void armDown() {
    	armMotorController1.set(-1.0);
    	armMotorController2.set(1.0);
    }
}

