// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1571.NewRobot.subsystems;

import org.usfirst.frc1571.NewRobot.RobotMap;
import org.usfirst.frc1571.NewRobot.commands.*;
import edu.wpi.first.wpilibj.*;
import org.usfirst.frc1571.NewRobot.Robot;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Drive extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController LeftDrive1 = RobotMap.driveSpeedController1;
    SpeedController LeftDrive2 = RobotMap.driveSpeedController2;
    RobotDrive robotDrive41 = RobotMap.driveRobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new DriveWithJoystick());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void DriveWithJoystick() {
    	
    	robotDrive41.arcadeDrive(Robot.oi.mainStick);
    	
    }
    //if sean sucks then quit robotics else stay in robotics but still have a bad time because sean still actually sucks
    //jkjk all hail overlord yumsauce may his nutz live on forever, deez nuts
    public void stop() {
    	robotDrive41.drive(0, 0);
    }
}	

